# This template creates a S3 bucket.
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html
# Cost must be always evaluated.
Description: Creates a S3 Bucket

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption: # bucket cryptography is a optional setting, but always a good practise.
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: fiorott-bucket-2020-11 # Must be a unique name across all AWS buckets
      VersioningConfiguration:
        Status: Enabled

      # For aditional bucket properties, check the documentation below:
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
