# This template creates a S3 bucket.
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html
# Cost must be always evaluated.
Description: Creates a S3 Bucket

Resources:

  MeuPrimeiroBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption: # bucket cryptography is a optional setting, but always a good practise.
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: bucket_repo_aws_2020_10 # Must be a unique name across all AWS buckets

      # For aditional bucket properties, check the documentation below:
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
